-- Add missing tables for parser functionality

-- Table for anime-country relations
CREATE TABLE IF NOT EXISTS anime_countries (
  anime_id BIGINT NOT NULL REFERENCES animes(id) ON DELETE CASCADE,
  country_id BIGINT NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  PRIMARY KEY (anime_id, country_id)
);

-- Table for translations/voice-overs
CREATE TABLE IF NOT EXISTS translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anime_id BIGINT NOT NULL REFERENCES animes(id) ON DELETE CASCADE,
  kodik_id TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  type TEXT,
  quality TEXT,
  player_link TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for new tables
ALTER TABLE anime_countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE translations ENABLE ROW LEVEL SECURITY;

-- RLS policies for anime_countries
CREATE POLICY "Allow read access for all users" ON anime_countries
  FOR SELECT USING (true);

CREATE POLICY "Allow insert/update for service role" ON anime_countries
  FOR ALL USING (true);

-- RLS policies for translations
CREATE POLICY "Allow read access for all users" ON translations
  FOR SELECT USING (true);

CREATE POLICY "Allow insert/update for service role" ON translations
  FOR ALL USING (true);

-- Enable RLS for anime_genres and anime_studios if not already
ALTER TABLE anime_genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE anime_studios ENABLE ROW LEVEL SECURITY;

-- Add policies for anime_genres
CREATE POLICY IF NOT EXISTS "Allow read access for all users" ON anime_genres
  FOR SELECT USING (true);

CREATE POLICY IF NOT EXISTS "Allow insert/update for service role" ON anime_genres
  FOR ALL USING (true);

-- Add policies for anime_studios
CREATE POLICY IF NOT EXISTS "Allow read access for all users" ON anime_studios
  FOR SELECT USING (true);

CREATE POLICY IF NOT EXISTS "Allow insert/update for service role" ON anime_studios
  FOR ALL USING (true);

-- Enable RLS for user_anime_lists and profiles
ALTER TABLE user_anime_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- RLS policies for user_anime_lists
CREATE POLICY "Users can view own lists" ON user_anime_lists
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own lists" ON user_anime_lists
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own lists" ON user_anime_lists
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own lists" ON user_anime_lists
  FOR DELETE USING (auth.uid() = user_id);

-- RLS policies for profiles
CREATE POLICY "Users can view all profiles" ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_animes_shikimori_id ON animes(shikimori_id);
CREATE INDEX IF NOT EXISTS idx_animes_title ON animes(title);
CREATE INDEX IF NOT EXISTS idx_translations_anime_id ON translations(anime_id);
CREATE INDEX IF NOT EXISTS idx_user_anime_lists_user_id ON user_anime_lists(user_id);
CREATE INDEX IF NOT EXISTS idx_user_anime_lists_anime_id ON user_anime_lists(anime_id);
