-- 1. ОСНОВНАЯ ТАБЛИЦА ДЛЯ АНИМЕ
CREATE TABLE animes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kodik_id TEXT UNIQUE,
  shikimori_id TEXT UNIQUE,
  kinopoisk_id TEXT,
  title TEXT,
  title_orig TEXT,
  year INT,
  poster_url TEXT,
  player_link TEXT,
  description TEXT,
  type TEXT,
  status TEXT,
  episodes_count INT,
  rating_mpaa TEXT,
  kinopoisk_rating NUMERIC(3, 1),
  imdb_rating NUMERIC(3, 1),
  shikimori_rating NUMERIC(3, 1),
  kinopoisk_votes INT,
  shikimori_votes INT,
  screenshots JSONB,
  updated_at_kodik TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ТАБЛИЦЫ-СПРАВОЧНИКИ
CREATE TABLE genres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE studios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- 3. СВЯЗУЮЩАЯ ТАБЛИЦА
CREATE TABLE anime_relations (
  anime_id BIGINT NOT NULL REFERENCES animes(id) ON DELETE CASCADE,
  relation_id BIGINT NOT NULL,
  relation_type TEXT NOT NULL,
  PRIMARY KEY (anime_id, relation_id, relation_type)
);

-- 4. ИНДЕКСЫ ДЛЯ УСКОРЕНИЯ РАБОТЫ
CREATE INDEX idx_animes_year ON animes(year);
CREATE INDEX idx_animes_type ON animes(type);
CREATE INDEX idx_animes_status ON animes(status);
CREATE INDEX idx_animes_episodes_count ON animes(episodes_count);
CREATE INDEX idx_animes_shikimori_rating ON animes(shikimori_rating);
CREATE INDEX idx_animes_kinopoisk_rating ON animes(kinopoisk_rating);
CREATE INDEX idx_animes_shikimori_votes ON animes(shikimori_votes);
CREATE INDEX idx_anime_relations_reverse ON anime_relations(relation_id, relation_type);

-- 5. RLS (Row Level Security) политики для безопасности
ALTER TABLE animes ENABLE ROW LEVEL SECURITY;
ALTER TABLE genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE studios ENABLE ROW LEVEL SECURITY;
ALTER TABLE countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE anime_relations ENABLE ROW LEVEL SECURITY;

-- Политики для чтения (все могут читать)
CREATE POLICY "Allow read access for all users" ON animes FOR SELECT USING (true);
CREATE POLICY "Allow read access for all users" ON genres FOR SELECT USING (true);
CREATE POLICY "Allow read access for all users" ON studios FOR SELECT USING (true);
CREATE POLICY "Allow read access for all users" ON countries FOR SELECT USING (true);
CREATE POLICY "Allow read access for all users" ON anime_relations FOR SELECT USING (true);

-- Политики для записи (только для сервисной роли)
CREATE POLICY "Allow insert/update for service role" ON animes FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow insert/update for service role" ON genres FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow insert/update for service role" ON studios FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow insert/update for service role" ON countries FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow insert/update for service role" ON anime_relations FOR ALL USING (auth.role() = 'service_role');
