name: CI

on:
  push:
    branches: [ main, develop, anihub-1.02 ]
  pull_request:
    branches: [ main, develop, anihub-1.02 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint (skipped if no ESLint config)
        if: ${{ hashFiles('**/.eslintrc*') != '' }}
        run: pnpm lint

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          KODIK_API_TOKEN: ${{ secrets.KODIK_API_TOKEN }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_GA_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
          MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
          MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
          MEILISEARCH_INDEX: ${{ secrets.MEILISEARCH_INDEX }}
        run: pnpm build

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run E2E smoke tests
        run: pnpm test:e2e
        env:
          BASE_URL: http://localhost:3000


